In [1]:

from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"


class display(object):
    """Display HTML representation of multiple objects"""

    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""

    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(
            self.template.format(a, eval(a)._repr_html_()) for a in self.args
        )

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a)) for a in self.args)



In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a

b = a.flatten()
b
c = a.flatten('F')
c

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

array([1, 4, 2, 5, 3, 6])

In [3]:
from eos.data_io.pool.parquet_pool import ParquetPool
from eos.data_io.pool.avro_pool import AvroPool 
from eos.data_io.pool.dask_pool import DaskPool
from eos.data_io.pool.mongo_pool import MongoPool

2023-08-21 09:07:28.474674: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
from eos.data_io.buffer.mongo_buffer import MongoBuffer

In [5]:
from eos.data_io.buffer.dask_buffer import DaskBuffer

In [6]:
# from dataclasses import dataclass, field
# from typing import Optional
# import pandas as pd
# import numpy as np
# from ordered_set import OrderedSet
from eos.data_io.config import drivers, trucks_by_id, drivers_by_id

# DriverSet = OrderedSet(
#     [
#         'wang-cheng',
#         'li-changlong',
#         'chen-hongmei',
#         'zheng-longfei',
#     ]
# )
# DriverSet[0]
# DriverSet.get_loc('wang-cheng')
# DriverSet


In [7]:
from eos.data_io.struct import StateSpecsCloud, StateSpecsField


In [8]:
from dataclasses import asdict
state_specs = StateSpecsCloud()
print(asdict(state_specs))

state_specs = StateSpecsField()
print(asdict(state_specs))



{'state_unit_codes': StateUnitCodes(velocity_unit_code='kph', thrust_unit_code='pct', brake_unit_code='pct'), 'state_number': 3, 'unit_number_per_state': 200, 'unit_duration': 4, 'frequency': 50, 'cloud_interface': CloudMixin(cloud_signal_frequency=50, cloud_gear_frequency=2, cloud_unit_duration=1, cloud_unit_number=4)}
{'state_unit_codes': StateUnitCodes(velocity_unit_code='kph', thrust_unit_code='pct', brake_unit_code='pct'), 'state_number': 3, 'unit_number_per_state': 30, 'unit_duration': 1.5, 'frequency': 20, 'field_interface': FieldMixin(field_observation_number=30, field_observation_frequency=20, field_countdown=3)}


In [9]:
import pandas as pd
import numpy as np
from datetime import datetime

ts = pd.to_datetime(datetime.now())
ts_ind = ts + pd.to_timedelta(np.arange(2), 'H')
ts_ind
df = pd.DataFrame(a, index=ts_ind, columns=['c1', 'c2', 'c3'])
df
df.index[0]


DatetimeIndex(['2023-08-21 09:07:29.919137', '2023-08-21 10:07:29.919137'], dtype='datetime64[ns]', freq=None)

c1  c2  c3
2023-08-21 09:07:29.919137   1   2   3
2023-08-21 10:07:29.919137   4   5   6

Timestamp('2023-08-21 09:07:29.919137')

In [10]:
ts
ts_end = pd.to_datetime(datetime.now())
ts_end
span = ts_end - ts
span
span_each_row = span / 4
span_each_row
np.linspace(0, 4, 5)
ts_ser = ts + pd.to_timedelta(np.linspace(1, 4, 4) * span_each_row, unit='s')
ts_ser


Timestamp('2023-08-21 09:07:29.919137')

Timestamp('2023-08-21 09:07:29.964832')

Timedelta('0 days 00:00:00.045695')

Timedelta('0 days 00:00:00.011423750')

array([0., 1., 2., 3., 4.])

DatetimeIndex(['2023-08-21 09:07:29.930560750',
               '2023-08-21 09:07:29.941984500',
               '2023-08-21 09:07:29.953408250',
                  '2023-08-21 09:07:29.964832'],
              dtype='datetime64[ns]', freq=None)

In [11]:
df_ts = pd.DataFrame(np.array([ts]), columns=['timestamp'])
df_ts

timestamp
0 2023-08-21 09:07:29.919137

In [12]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Generate state

In [13]:
ss = np.arange(12)
a1 = ss[:4].tolist()
a2 = ss[4:8].tolist()
a3 = ss[8:].tolist()
ss = [a1, a2, a3]
ss
df_s = pd.DataFrame(ss, columns=['t', 'v', 'p', 'b'])  # .set_index('t')
df_s

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

t  v   p   b
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [14]:
np.arange(0, 4 * 20, 20)

array([ 0, 20, 40, 60])

In [15]:
ts_ind = ts + pd.to_timedelta(np.arange(0, 4 * 20, 20), 'ms')
ts_ind
ss = np.arange(12)
a1 = ss[:4]
a2 = ss[4:8]
a3 = ss[8:]
df_ss = pd.DataFrame(
    {'timestep': ts_ind, 'velocity': a1, 'thrust': a2, 'brake': a3}
)  # .set_index('timestep')
df_ss.columns.name = 'qtuple'
df_ss
df_ss[['velocity', 'thrust', 'brake']]

DatetimeIndex(['2023-08-21 09:07:29.919137', '2023-08-21 09:07:29.939137',
               '2023-08-21 09:07:29.959137', '2023-08-21 09:07:29.979137'],
              dtype='datetime64[ns]', freq=None)

qtuple                   timestep  velocity  thrust  brake
0      2023-08-21 09:07:29.919137         0       4      8
1      2023-08-21 09:07:29.939137         1       5      9
2      2023-08-21 09:07:29.959137         2       6     10
3      2023-08-21 09:07:29.979137         3       7     11

qtuple  velocity  thrust  brake
0              0       4      8
1              1       5      9
2              2       6     10
3              3       7     11

In [16]:
npa_ss_flatten = df_ss[['velocity', 'thrust', 'brake']].to_numpy().flatten()
npa_ss_flatten

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [17]:
ui_t = df_ss.loc[:, ['velocity', 'thrust']]
ui_t
power_t = ui_t.prod(axis=1)
power_t
power_t.sum()

qtuple  velocity  thrust
0              0       4
1              1       5
2              2       6
3              3       7

0     0
1     5
2    12
3    21
dtype: int64

38

In [18]:
state = df_ss.stack().swaplevel(0, 1)
state.name = 'state'
state.index.names = ['rows', 'idx']
state.sort_index(inplace=True)
state

rows      idx
brake     0                               8
          1                               9
          2                              10
          3                              11
thrust    0                               4
          1                               5
          2                               6
          3                               7
timestep  0      2023-08-21 09:07:29.919137
          1      2023-08-21 09:07:29.939137
          2      2023-08-21 09:07:29.959137
          3      2023-08-21 09:07:29.979137
velocity  0                               0
          1                               1
          2                               2
          3                               3
Name: state, dtype: object

In [19]:
state[['velocity', 'thrust', 'brake']]

rows      idx
velocity  0       0
          1       1
          2       2
          3       3
thrust    0       4
          1       5
          2       6
          3       7
brake     0       8
          1       9
          2      10
          3      11
Name: state, dtype: object

In [20]:
# from functools import reduce
#
#
# velocity = pd.Series(ss[:4], name='velocity')
# thrust = pd.Series(ss[4:8], name='thrust')
# brake = pd.Series(ss[8:], name='brake')
# series = [velocity, thrust, brake]
# state = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# state = state.stack().swaplevel(0, 1).sort_index()
# state.name = 'state'
# state
# len(state)


In [21]:
# from functools import reduce
#
#
# velocity = pd.Series(s[:4], name='velocity')
# thrust = pd.Series(s[4:7], name='thrust')
# brake = pd.Series(s[7:], name='brake')
# series = [velocity, thrust, brake]
# state = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# state = state.stack().swaplevel(0, 1).sort_index()
# state.name = 'state'
# state
# len(state)
#
#

### generate action

In [22]:
from functools import reduce

a = len(ss) + np.arange(15)
speed_ser = pd.Series(np.linspace(40, 60, 3), name='speed')
# row_ser
row_dict = {f'r{i}': a[i * 5 : i * 5 + 5] for i in np.arange(3)}
row_dict
row_array = a.reshape(3, 5).transpose()
row_array
rows_df = pd.DataFrame(row_array)
rows_df.columns = [f'r{i}' for i in np.arange(3)]
rows_df

action_row_names = [f'r{i}' for i in np.arange(3)]
action_row_names

{'r0': array([12, 13, 14, 15, 16]),
 'r1': array([17, 18, 19, 20, 21]),
 'r2': array([22, 23, 24, 25, 26])}

array([[12, 17, 22],
       [13, 18, 23],
       [14, 19, 24],
       [15, 20, 25],
       [16, 21, 26]])

r0  r1  r2
0  12  17  22
1  13  18  23
2  14  19  24
3  15  20  25
4  16  21  26

['r0', 'r1', 'r2']

In [23]:

ts_ind = ts + pd.to_timedelta(np.arange(5 * 20, 8 * 20, 20), 'ms')
ts_ser = pd.Series(ts_ind, name='timestep')
throttle_ser = pd.Series(np.linspace(0, 1.0, 5), name='throttle')
# throttle_ser
dfs = [rows_df, ts_ser, speed_ser, throttle_ser]
action = (
    reduce(
        lambda left, right: pd.merge(
            left, right, how='outer', left_index=True, right_index=True
        ),
        dfs,
    )
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)

action.name = 'action'
action.index.names = ['rows', 'idx']
action.index
action
# action = pd.concat([df.DataFrame(row_dict),df.Series(row_ind),df.Series(ts_ind),df.Series(pedal_ind)],axis=1)
# action
# pedal_ind
# action_ind = pd.MultiIndex.from_product([row_ind, ts_ind], names=['row', 'timestamp'])
# a
# speed_row, row_name = *row_dict
# action = (
#     pd.DataFrame(
#         {
#             **row_dict,
#             'throttle': pedal_ind,
#             'speed': [r[1] for r in row_ind],
#         }
#     )  # .set_index('pedal')
#     # .stack()
#     # .swaplevel(0, 1)
#     .sort_index()
# )
# action
# action.columns
# action.columns = pd.MultiIndex.from_arrays(
#     [action.columns, ts_ind], names=['nominalspeed', 'timestep']
# )
# action = action.stack([0, 1]).swaplevel(0, 1).swaplevel(1, 2).sort_index()
# action.name = 'action'
# # action.index.names = ['nominalspeed', 'timestamp']
# # action.index
# action

MultiIndex([(      'r0', 0),
            (      'r0', 1),
            (      'r0', 2),
            (      'r0', 3),
            (      'r0', 4),
            (      'r1', 0),
            (      'r1', 1),
            (      'r1', 2),
            (      'r1', 3),
            (      'r1', 4),
            (      'r2', 0),
            (      'r2', 1),
            (      'r2', 2),
            (      'r2', 3),
            (      'r2', 4),
            (   'speed', 0),
            (   'speed', 1),
            (   'speed', 2),
            ('throttle', 0),
            ('throttle', 1),
            ('throttle', 2),
            ('throttle', 3),
            ('throttle', 4),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2)],
           names=['rows', 'idx'])

rows      idx
r0        0                              12
          1                              13
          2                              14
          3                              15
          4                              16
r1        0                              17
          1                              18
          2                              19
          3                              20
          4                              21
r2        0                              22
          1                              23
          2                              24
          3                              25
          4                              26
speed     0                            40.0
          1                            50.0
          2                            60.0
throttle  0                             0.0
          1                            0.25
          2                             0.5
          3                            0.75
          4       

In [24]:
action[['r0', 'r1', 'r2']]

rows  idx
r0    0      12
      1      13
      2      14
      3      15
      4      16
r1    0      17
      1      18
      2      19
      3      20
      4      21
r2    0      22
      1      23
      2      24
      3      25
      4      26
Name: action, dtype: object

In [25]:
# a = len(state) + np.arange(6)
# ar0 = pd.Series(a[:2], name='row0')
# ar1 = pd.Series(a[2:4], name='row1')
# ar2 = pd.Series(a[4:], name='row2')
# series = [ar0, ar1, ar2]
# action = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# action = action.stack().swaplevel(0, 1).sort_index()
# action.name = 'action'
# action
# len(action) + len(state)

In [26]:
reward = (
    pd.DataFrame({'work': len(ss) + len(a), 'timestep': ts_ind[0]}, index=[0])
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)
# reward_index = (reward.name,  ts_ind[0], 0)
reward.index.names = ['rows', 'idx']
reward.name = 'reward'
reward.index
reward
# reward.name = 'reward'

MultiIndex([('timestep', 0),
            (    'work', 0)],
           names=['rows', 'idx'])

rows      idx
timestep  0      2023-08-21 09:07:30.019137
work      0                              27
Name: reward, dtype: object

In [27]:
reward['work'][0]
reward.loc[('work', 0)]

27

27

In [28]:
# velocity = pd.Series(len(state) + len(action) + len(reward) + s[:4], name='velocity')
# thrust = pd.Series(len(state) + len(action) + len(reward) + s[4:7], name='thrust')
# brake = pd.Series(len(state) + len(action) + len(reward) + s[7:], name='brake')
# series = [velocity, thrust, brake]
# nstate = reduce(
#     lambda x, y: pd.merge(x, y, how='outer', left_index=True, right_index=True), series
# )
# nstate = nstate.stack().swaplevel(0, 1).sort_index()
# nstate.name = 'nstate'
# nstate
# len(nstate)
ts_ind = ts + pd.to_timedelta(5, 's') + pd.to_timedelta(np.arange(0, 4 * 20, 20), 'ms')
ts_ind
ss = np.arange(12) + len(ss) + len(a) + len(reward)
a1 = ss[:4]
a2 = ss[4:8]
a3 = ss[8:]
nstate = (
    pd.DataFrame({'timestep': ts_ind, 'velocity': a1, 'thrust': a2, 'brake': a3})
    # .set_index('timestamp')
    .stack()
    .swaplevel(0, 1)
    .sort_index()
)
nstate.name = 'nstate'
nstate.index.names = ['rows', 'idx']
len(nstate)
nstate

DatetimeIndex(['2023-08-21 09:07:34.919137', '2023-08-21 09:07:34.939137',
               '2023-08-21 09:07:34.959137', '2023-08-21 09:07:34.979137'],
              dtype='datetime64[ns]', freq=None)

16

rows      idx
brake     0                              37
          1                              38
          2                              39
          3                              40
thrust    0                              33
          1                              34
          2                              35
          3                              36
timestep  0      2023-08-21 09:07:34.919137
          1      2023-08-21 09:07:34.939137
          2      2023-08-21 09:07:34.959137
          3      2023-08-21 09:07:34.979137
velocity  0                              29
          1                              30
          2                              31
          3                              32
Name: nstate, dtype: object

In [29]:
timestamp = pd.Series([ts], name='timestamp')
timestamp.index = pd.MultiIndex.from_product(
    [timestamp.index, [0]], names=['rows', 'idx']
)
timestamp.index
state.index
action.index
reward.index
nstate.index

MultiIndex([(0, 0)],
           names=['rows', 'idx'])

MultiIndex([(   'brake', 0),
            (   'brake', 1),
            (   'brake', 2),
            (   'brake', 3),
            (  'thrust', 0),
            (  'thrust', 1),
            (  'thrust', 2),
            (  'thrust', 3),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2),
            ('timestep', 3),
            ('velocity', 0),
            ('velocity', 1),
            ('velocity', 2),
            ('velocity', 3)],
           names=['rows', 'idx'])

MultiIndex([(      'r0', 0),
            (      'r0', 1),
            (      'r0', 2),
            (      'r0', 3),
            (      'r0', 4),
            (      'r1', 0),
            (      'r1', 1),
            (      'r1', 2),
            (      'r1', 3),
            (      'r1', 4),
            (      'r2', 0),
            (      'r2', 1),
            (      'r2', 2),
            (      'r2', 3),
            (      'r2', 4),
            (   'speed', 0),
            (   'speed', 1),
            (   'speed', 2),
            ('throttle', 0),
            ('throttle', 1),
            ('throttle', 2),
            ('throttle', 3),
            ('throttle', 4),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2)],
           names=['rows', 'idx'])

MultiIndex([('timestep', 0),
            (    'work', 0)],
           names=['rows', 'idx'])

MultiIndex([(   'brake', 0),
            (   'brake', 1),
            (   'brake', 2),
            (   'brake', 3),
            (  'thrust', 0),
            (  'thrust', 1),
            (  'thrust', 2),
            (  'thrust', 3),
            ('timestep', 0),
            ('timestep', 1),
            ('timestep', 2),
            ('timestep', 3),
            ('velocity', 0),
            ('velocity', 1),
            ('velocity', 2),
            ('velocity', 3)],
           names=['rows', 'idx'])

In [30]:
timestamp_index = (timestamp.name, '', 0)
# timestamp_index
state_index = [(state.name, *i) for i in state.index]
# state_index
reward_index = [(reward.name, *i) for i in reward.index]
# reward_index
action_index = [(action.name, *i) for i in action.index]
# action_index
nstate_index = [(nstate.name, *i) for i in nstate.index]
# nstate_index

multiindex = pd.MultiIndex.from_tuples(
    [timestamp_index, *state_index, *action_index, *reward_index, *nstate_index]
)
multiindex


MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

In [31]:
timestamp.index
timestamp.values
timestamp

MultiIndex([(0, 0)],
           names=['rows', 'idx'])

array(['2023-08-21T09:07:29.919137000'], dtype='datetime64[ns]')

rows  idx
0     0     2023-08-21 09:07:29.919137
Name: timestamp, dtype: datetime64[ns]

In [32]:
observation_list = [timestamp, state, action, reward, nstate]
observation = pd.concat(observation_list)
observation.index = multiindex
observation
# observation.dtype

timestamp            0    2023-08-21 09:07:29.919137
state      brake     0                             8
                     1                             9
                     2                            10
                     3                            11
                                     ...            
nstate     timestep  3    2023-08-21 09:07:34.979137
           velocity  0                            29
                     1                            30
                     2                            31
                     3                            32
Length: 61, dtype: object

In [33]:
idx = pd.IndexSlice
# observation_sorted = observation.sort_index()
actions = observation.sort_index().loc[idx['action', action_row_names, :]].values.astype(np.float32)
actions
actions.dtype

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26.], dtype=float32)

dtype('float32')

In [34]:
import tensorflow as tf
# actions = tf.convert_to_tensor(actions, dtype=tf.float32)
actions
last_actions = tf.expand_dims(tf.expand_dims(actions, axis=0), axis=0)
last_actions

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26.], dtype=float32)

2023-08-21 09:07:30.370507: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-21 09:07:31.837997: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-08-21 09:07:31.838289: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

<tf.Tensor: shape=(1, 1, 15), dtype=float32, numpy=
array([[[12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26.]]], dtype=float32)>

In [35]:
states = observation.sort_index().loc[idx['state', ['velocity', 'thrust', 'brake'] ,:]].values.astype(np.float32)
states = tf.expand_dims(tf.expand_dims(tf.convert_to_tensor(states, dtype=tf.float32), axis=0),axis=0)
states

<tf.Tensor: shape=(1, 1, 12), dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]],
      dtype=float32)>

In [36]:
observation.index

MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

In [37]:

observation0 = observation.copy()
observation0.loc['timestamp', '', 0] = ts + pd.Timedelta(1, 'h')
observation1 = observation.copy()
observation1.loc['timestamp', '', 0] = ts + pd.Timedelta(2, 'h')
observation2 = observation.copy()
observation2.loc['timestamp', '', 0] = ts + pd.Timedelta(3, 'h')
observation3 = observation.copy()
observation3.loc['timestamp', '', 0] = ts + pd.Timedelta(4, 'h')
observation4 = observation.copy()
observation4.loc['timestamp', '', 0] = ts + pd.Timedelta(5, 'h')
observation_list = [
    observation0,
    observation1,
    observation2,
    observation3,
    observation4,
]


In [38]:

dfs_epi = pd.concat(observation_list, axis=1).transpose()
dfs_epi.columns.names = ['qtuple', 'rows', 'idx']
dfs_epi.columns
dfs_epi


MultiIndex([('timestamp',         '', 0),
            (    'state',    'brake', 0),
            (    'state',    'brake', 1),
            (    'state',    'brake', 2),
            (    'state',    'brake', 3),
            (    'state',   'thrust', 0),
            (    'state',   'thrust', 1),
            (    'state',   'thrust', 2),
            (    'state',   'thrust', 3),
            (    'state', 'timestep', 0),
            (    'state', 'timestep', 1),
            (    'state', 'timestep', 2),
            (    'state', 'timestep', 3),
            (    'state', 'velocity', 0),
            (    'state', 'velocity', 1),
            (    'state', 'velocity', 2),
            (    'state', 'velocity', 3),
            (   'action',       'r0', 0),
            (   'action',       'r0', 1),
            (   'action',       'r0', 2),
            (   'action',       'r0', 3),
            (   'action',       'r0', 4),
            (   'action',       'r1', 0),
            (   'action',       'r

qtuple                   timestamp state                             \
rows                               brake            thrust            
idx                              0     0  1   2   3      0  1  2  3   
0       2023-08-21 10:07:29.919137     8  9  10  11      4  5  6  7   
1       2023-08-21 11:07:29.919137     8  9  10  11      4  5  6  7   
2       2023-08-21 12:07:29.919137     8  9  10  11      4  5  6  7   
3       2023-08-21 13:07:29.919137     8  9  10  11      4  5  6  7   
4       2023-08-21 14:07:29.919137     8  9  10  11      4  5  6  7   

qtuple                              ... nstate      \
rows                      timestep  ... thrust       
idx                              0  ...      2   3   
0       2023-08-21 09:07:29.919137  ...     35  36   
1       2023-08-21 09:07:29.919137  ...     35  36   
2       2023-08-21 09:07:29.919137  ...     35  36   
3       2023-08-21 09:07:29.919137  ...     35  36   
4       2023-08-21 09:07:29.919137  ...     35  36   

qtuple                                                          \
rows                      timestep                               
idx                              0                           1   
0       2023-08-21 09:07:34.919137  2023-08-21 09:07:34.939137   
1       2023-08-21 09:07:34.919137  2023-08-21 09:07:34.939137   
2       2023-08-21 09:07:34.919137  2023-08-21 09:07:34.939137   
3       2023-08-21 09:07:34.919137  2023-08-21 09:07:34.939137   
4       2023-08-21 09:07:34.919137  2023-08-21 09:07:34.939137   

qtuple                                                                       \
rows                                                           velocity       
idx                              2                           3        0   1   
0       2023-08-21 09:07:34.959137  2023-08-21 09:07:34.979137       29  30   
1       2023-08-21 09:07:34.959137  2023-08-21 09:07:34.979137       29  30   
2       2023-08-21 09:07:34.959137  2023-08-21 09:07:34.979137       29  30   
3       2023-08-21 09:07:34.959137  2023-08-21 09:07:34.979137       29  30   
4       2023-08-21 09:07:34.959137  2023-08-21 09:07:34.979137       29  30   

qtuple          
rows            
idx      2   3  
0       31  32  
1       31  32  
2       31  32  
3       31  32  
4       31  32  

[5 rows x 61 columns]

In [39]:
dfs_episode1 = dfs_epi.copy().sort_index(axis=1)
dfs_episode1.set_index(('timestamp', '', 0), inplace=True)
dfs_episode1.index.name = 'timestamp'
idx = pd.IndexSlice
dfs_episode1

qtuple                     action                                      ...  \
rows                           r0                  r1                  ...   
idx                             0   1   2   3   4   0   1   2   3   4  ...   
timestamp                                                              ...   
2023-08-21 10:07:29.919137     12  13  14  15  16  17  18  19  20  21  ...   
2023-08-21 11:07:29.919137     12  13  14  15  16  17  18  19  20  21  ...   
2023-08-21 12:07:29.919137     12  13  14  15  16  17  18  19  20  21  ...   
2023-08-21 13:07:29.919137     12  13  14  15  16  17  18  19  20  21  ...   
2023-08-21 14:07:29.919137     12  13  14  15  16  17  18  19  20  21  ...   

qtuple                      state                                 \
rows                       thrust                       timestep   
idx                             2  3                           0   
timestamp                                                          
2023-08-21 10:07:29.919137      6  7  2023-08-21 09:07:29.919137   
2023-08-21 11:07:29.919137      6  7  2023-08-21 09:07:29.919137   
2023-08-21 12:07:29.919137      6  7  2023-08-21 09:07:29.919137   
2023-08-21 13:07:29.919137      6  7  2023-08-21 09:07:29.919137   
2023-08-21 14:07:29.919137      6  7  2023-08-21 09:07:29.919137   

qtuple                                                  \
rows                                                     
idx                                                  1   
timestamp                                                
2023-08-21 10:07:29.919137  2023-08-21 09:07:29.939137   
2023-08-21 11:07:29.919137  2023-08-21 09:07:29.939137   
2023-08-21 12:07:29.919137  2023-08-21 09:07:29.939137   
2023-08-21 13:07:29.919137  2023-08-21 09:07:29.939137   
2023-08-21 14:07:29.919137  2023-08-21 09:07:29.939137   

qtuple                                                  \
rows                                                     
idx                                                  2   
timestamp                                                
2023-08-21 10:07:29.919137  2023-08-21 09:07:29.959137   
2023-08-21 11:07:29.919137  2023-08-21 09:07:29.959137   
2023-08-21 12:07:29.919137  2023-08-21 09:07:29.959137   
2023-08-21 13:07:29.919137  2023-08-21 09:07:29.959137   
2023-08-21 14:07:29.919137  2023-08-21 09:07:29.959137   

qtuple                                                                    
rows                                                   velocity           
idx                                                  3        0  1  2  3  
timestamp                                                                 
2023-08-21 10:07:29.919137  2023-08-21 09:07:29.979137        0  1  2  3  
2023-08-21 11:07:29.919137  2023-08-21 09:07:29.979137        0  1  2  3  
2023-08-21 12:07:29.919137  2023-08-21 09:07:29.979137        0  1  2  3  
2023-08-21 13:07:29.919137  2023-08-21 09:07:29.979137        0  1  2  3  
2023-08-21 14:07:29.919137  2023-08-21 09:07:29.979137        0  1  2  3  

[5 rows x 60 columns]

In [40]:
dfs_episode1.loc[:, idx['action':'state', :, :, :]] = dfs_episode1.loc[
    :, idx['action':'state', :, :, :]
].astype('int')
dfs_episode1
dfs_episode1.dtypes
dfs_episode1.columns

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Timestamp'

### Convert columns types to float

In [ ]:
dfs_epi
dfs_episode = dfs_epi.copy()
dfs_episode.index
dfs_episode.set_index(('timestamp', '', 0), inplace=True)
dfs_episode.sort_index(axis=1, inplace=True)
dfs_episode.index
dfs_episode


In [ ]:
dfs_episode.index.name = 'timestamp'
idx = pd.IndexSlice

# # dfs_episode = dfs_episode.astype({idx['state', 'velocity', :]: 'int'})  # Error unhashable type: 'slice' for dictionary
# # sorted_idx = **(idx['state', :, :]:'int')
# # sorted_idx
# dfs_episode.loc[:, idx['state', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
#     :, idx['state', ['brake', 'thrust', 'velocity'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# dfs_episode.loc[:, idx['action', ['r0', 'r1', 'r2'], :]] = dfs_episode.loc[
#     :, idx['action', ['r0', 'r1', 'r2'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
# # dfs_episode['action'] = dfs_episode['action'].astype('float')
# # dfs_episode['reward'] = dfs_episode['reward'].astype('float')
# dfs_episode.loc[:, idx['reward', 'work', 0]] = dfs_episode.loc[
#     :, idx['reward', 'work', 0]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# # dfs_episode['nstate'] = dfs_episode['nstate'].astype('float')
# dfs_episode.loc[:, idx['nstate', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
#     :, idx['nstate', ['brake', 'thrust', 'velocity'], :]
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
state_cols_float = [('state', col) for col in ['brake', 'thrust', 'velocity']]
action_cols_float = [('action', col) for col in ['r0', 'r1', 'r2', 'speed', 'throttle']]
reward_cols_float = [('reward', 'work')]
nstate_cols_float = [('nstate', col) for col in ['brake', 'thrust', 'velocity']]
for col in action_cols_float + state_cols_float + reward_cols_float + nstate_cols_float:
    dfs_episode[col[0], col[1]] = dfs_episode[col[0], col[1]].astype(
        'float'
    )  # float16 not allowed in parquet
dfs_episode
dfs_episode.dtypes
# dfs_episode.columns
# dfs_epi
# dfs_episode


## prepend two levels of index "vehicle" and "driver" to the DataFrame object

In [ ]:
dfs_episode = pd.concat(
    [dfs_episode], keys=[drivers_by_id['wang-cheng'].pid], names=['driver']
)
dfs_episode = pd.concat(
    [dfs_episode], keys=[trucks_by_id['VB7'].vid], names=['vehicle']
)

In [ ]:
dfs_episode.index
dfs_episode.columns

In [ ]:

# dfs_episode.columns.set_names(
#     [
#         'qtuple',
#         'rows',
#         'idx',
#     ],
#     level=[0, 1, 2],
#     inplace=True,
# )
dfs_episode
dfs_episode.dtypes


In [ ]:
# dfs_episode['state', 'thrust'] = dfs_episode['state', 'thrust'].astype('float')
# # dfs_episode.loc[:, idx['state', ['brake', 'thrust', 'velocity'], :]] = dfs_episode.loc[
# #     :, idx['state', ['brake', 'thrust', 'velocity'], :]
# # ].astype(
# #     'float'
# # )  # float16 not allowed in parquet
# dfs_episode.loc[:, ('state', ['brake', 'thrust', 'velocity'])] = dfs_episode.loc[
#     :, ('state', ['brake', 'thrust', 'velocity'])
# ].astype(
#     'float'
# )  # float16 not allowed in parquet
# dfs_episode['action', 'r0'] = dfs_episode['action', 'r0'].astype(
#     'float'
# )  # float16 not allowed in parquet
#
# dfs_episode.dtypes

In [ ]:
# idx = pd.IndexSlice
# dfs_episode.loc[:, idx['state', :, :]] = dfs_episode.loc[:, idx['state', :, :]].astype(
#     'int'
# )
# dfs_episode.loc[:, idx['action', :, :]] = dfs_episode.loc[
#     :, idx['action', :, :]
# ].astype('float16')
# dfs_episode.loc[:, idx['reward', :, :]] = dfs_episode.loc[
#     :, idx['reward', :, :]
# ].astype('float16')
# dfs_episode.loc[:, idx['nstate', :, :]] = dfs_episode.loc[
#     :, idx['nstate', :, :]
# ].astype('float16')
#
# vel_1 = dfs_episode[[('state', 'velocity', 1)]]
# vel_1.dtypes
# vel_1.index
# vel_1.values
# # type(vel_1)
# vel_1.iloc[0]
# type(vel_1.iloc[0])
# type(vel_1.iloc[0].values[0])

## Add a level of index for episode

In [ ]:
episodestart = ts - pd.Timedelta(1, 'h')
dfs_episode = pd.concat([dfs_episode], keys=[ts], names=['episodestart'])
dfs_episode = dfs_episode.swaplevel(1, 0, axis=0)
dfs_episode = dfs_episode.swaplevel(1, 2, axis=0)
dfs_episode.sort_index(inplace=True)
dfs_episode.index
dfs_episode.columns
dfs_episode

In [ ]:
dfs_episode.dtypes

In [ ]:
vb7 = trucks_by_id['VB7']

### Encoding MultiIndexed DataFrame to documents array of MongoDB record type (nested dictionary)

In [ ]:
from eos.data_io.struct import ObservationMetaCloud, StateSpecs, StateUnitCodes, ActionSpecs, RewardSpecs

observation_meta = ObservationMetaCloud()
#     state_specs=StateSpecs(
#         interface='cloud',
#         state_unit_codes=StateUnitCodes(
#             state_unit_code='kph',
#             thrust_unit_code='pct',
#             brake_unit_code='pct',
#         ),
#         state_number =3,
#         unit_number_per_state = vb7.state_number_per_state,
#     ),
#     action_specs=ActionSpecs(
#         action_unit_code='nm',
#         action_row_number=trucks_by_id['VB7'].torque_table_row_num_flash,
#         action_column_number=len(trucks_by_id['VB7'].pedal_scale),
#     ),
#     reward_specs=RewardSpecs(
#         reward_unit_code='wh',
#         reward_number=1
#     ),
#     site=trucks_by_id['VB7'].site,
# )
observation_meta
observation_meta.model_dump()

In [ ]:
# dfs_episode
#
# records = dfs_episode.to_dict('records')
# # records
# record_nested = [[{key: value} for key, value in record.items()] for record in records]
# record_nested
# ser = dfs_episode.to_dict('split')
# ser

In [ ]:
# dict_nested = [{i: dfs_episode.xs(i).to_dict('index') for i in level} for level in dfs_episode.index.levels]
# dfs_index = dfs_episode.to_dict('index')
# dfs_index


def nest(d: dict) -> dict:
    result = {}
    for key, value in d.items():
        target = result
        for k in key[:-1]:
            target = target.setdefault(k, {})
        target[key[-1]] = value
    return result


def df_to_nested_dict(df_multi_indexed_col: pd.DataFrame) -> dict:
    d = df_multi_indexed_col.to_dict('index')
    return {k: nest(v) for k, v in d.items()}

def eos_df_to_nested_dict(episode: pd.DataFrame) -> dict:
    """
    Convert a eos dataframe with multi-indexed columns to a nested dictionary
    Remove all the levels of the multi-indexed columns except for 'timestamp'
    Keep only the timestamp as the single key for the nested dictionary
    """
    dict_nested = df_to_nested_dict(
        episode
    )  # for multi-indexed dataframe, the index in the first level of the dictionary is still a tuple!
    indices_dict = [
        {episode.index.names[i]: level for i, level in enumerate(levels)}
        for levels in episode.index
    ]  # all elements in the array should have the same vehicle, driver, episodestart
    single_key_dict = {
        idx['timestamp']: dict_nested[key]
        for idx, key in zip(indices_dict, dict_nested)
    }

    return single_key_dict
# dfs_episode
# dfs_episode.columns

# dict1 = {key: nest(value) for key, value in dfs_episode.to_dict('index').items()}
# dict1

dict_nested = eos_df_to_nested_dict(dfs_episode)
dict_nested
# dict_nested = {level:
#                    {i: dfs_episode.xs(i).to_dict('index') for i in level }
#                for level in dfs_episode.index.levels}
# dict_nested = {level: dfs_episode.xs(level).to_dict('index')
#                for level in dfs_episode.columns.levels[0]}
# dict_nested
len(dict_nested)

In [ ]:
# dict_df_xs = {level: dfs_episode.xs(level) for level in dfs_episode.index.levels[0]}
# dict_df_xs['VB7']
len(dict_nested)
dfs_episode
dict_nested

In [ ]:

indices = dfs_episode.index
indices.name
indices.names
indices
indices_dict = [
    {indices.names[i]: level for i, level in enumerate(levels)} for levels in indices
]
indices_dict
len(indices_dict)

In [ ]:
single_key_dict = [(idx['timestamp'], dict_nested[key]) for idx, key in zip(indices_dict, dict_nested)]
single_key_dict[3]
len(single_key_dict)


### Decode episode into one document of mongo episode type (nested dictionaries)


In [ ]:
from dataclasses import asdict
episode_meta = indices_dict[0].copy()
try:
    episode_meta.pop('timestamp')
except KeyError:
    print(f"Key 'timestamp' not found")

episode_meta['seq_len'] = len(single_key_dict)
print(episode_meta)
meta = {**(observation_meta.model_dump()), **episode_meta}
meta




In [ ]:
single_key_dict = {idx['timestamp']: dict_nested[key] for idx, key in zip(indices_dict, dict_nested)}

In [ ]:
from eos.data_io.struct import DataFrameDoc

doc = DataFrameDoc(
    timestamp=meta['episodestart'],
    meta=meta,
    observation=single_key_dict,
)
doc

In [ ]:
indices_dict[0]

In [ ]:
# from dataclasses import asdict
#
# rows_multi = [
#     {
#         'timestamp': idx['timestamp'],
#         'meta': {**idx, **(asdict(meta))},
#         'observation': {key: value for key, value in record.items()},
#     }
#     for (idx, record) in zip(indices_dict, records)
# ]
# rows_multi


### Encode the records of an episode into rows of nested dictionaries

In [ ]:
from dataclasses import asdict

rows = [
    {
        'timestamp': idx['timestamp'],
        'meta': {**idx, **(observation_meta.model_dump())},
        'observation': dict_nested[key],
    }
    for (idx, key) in zip(indices_dict, dict_nested)
]
rows
len(rows)

## Decoding MongoDB dict to MultiIndexed DataFrame

In [ ]:
df_rows = pd.DataFrame(rows)
df_rows
df_rows['observation'][0]

In [ ]:
dict_observations = [
    {key: value for key, value in row.items()} for row in df_rows['observation']
]
dict_observations

### Decoding MongoDB dict to MultiIndexed DataFrame
first get the multiindex as tuple from nested keys

In [ ]:

dict_observations = {(meta['episodestart'], meta['vehicle'], meta['driver'], meta['timestamp'], key1, key2, key3): value
                        for meta, obs in zip(df_rows['meta'],df_rows['observation'])
                        for key1, obs1 in obs.items()
                        for key2, obs2 in obs1.items()
                        for key3, value in obs2.items()}

dict_observations
len(dict_observations)

In [ ]:
ser_decoded = pd.Series(dict_observations)
ser_decoded.index.names = ['episodestart', 'vehicle', 'driver', 'timestamp', 'qtuple', 'rows', 'idx']
ser_decoded

In [ ]:
df_decoded = ser_decoded.unstack(level=['qtuple', 'rows', 'idx'])
df_decoded
df_decoded.columns
# df_decoded.reset_index()

In [ ]:
# df_decoded.reset_index()
# df_decoded

In [ ]:

# ser_action = ser_decoded.loc[('action', ['r0', 'r1', 'r2', 'throttle'])]
# df_action = ser_action.unstack(level=[4, 5])
idx = pd.IndexSlice
df_action = df_decoded.loc[:, idx['action', ['r0', 'r1', 'r2', 'throttle']]]
df_action
# df_action.set_index(('action', 'throttle'))5369@

### Decoding MongoDB dict to MultiIndexed fully described DataFrame

In [ ]:

dict_observations_list = [
    {
        (meta['episodestart'], meta['vehicle'], meta['driver'], meta['timestamp'], key1, key2, key3): value
        for key1, obs1 in obs.items()
        for key2, obs2 in obs1.items()
        for key3, value in obs2.items()
    }
    for meta, obs in zip(df_rows['meta'],df_rows['observation'])
]

dict_observations_list[0]
len(dict_observations_list)

In [ ]:
idx = pd.IndexSlice
ser_decoded = pd.Series(dict_observations_list[0])
ser_decoded.index.names =[ 'episodestart', 'vehicle', 'driver', 'timestamp', 'qtuple', 'rows', 'idx']
# ser_decoded
# ser_decoded.index
ser_action = ser_decoded.loc[idx[:, :, :, :, 'action', ['r0', 'r1', 'r2', 'throttle']]]
# ser_action.index
df_action = ser_action.unstack([0,1,2,3,4,5])
# df_action.index
# df_action.columns
multiindex = df_action.columns
# multiindex[0]
multiindex[-1]
# df_action.index.names
# multiindex = (*df_action.index.names,('action', 'throttle'))
# multiindex
df_action.set_index(multiindex[-1], inplace=True)
df_action
df_action.columns
# df_action.set_index(idx[:, :, :, :, 'action', 'throttle'], inplace=True)
# df_action = pd.concat([df_action], keys=[('action','throttle')], names=['qtuple', 'rows']).set
# multiindex = (df_action.index,'action', 'throttle'))
# df_action.set_index(multiindex, inplace=True)
# df_action

In [ ]:
action_timestep = ser_decoded.loc[idx[:,:,:,:,'action', 'timestep']]
action_timestep
action_speed = ser_decoded.loc[idx[:,:,:,:,'action', 'speed']]
action_speed
action_multicol = [
    (*column, speed, timestep)
    for column, timestep, speed in zip(df_action.columns, action_timestep, action_speed)
]
action_multicol

df_action.columns = pd.MultiIndex.from_tuples(
    action_multicol, names=['episodestart','vehicle','driver','timestamp','qtuple', 'rows', 'speed', 'timestep']
)
df_action
df_action.values.flatten()

In [ ]:
ser_state = ser_decoded.loc[idx[:,:,:,:,'state', ['brake', 'thrust', 'velocity', 'timestep']]]
# ser_state
df_state = ser_state.unstack([0,1,2,3,4,5])
# df_state = ser_state.unstack(level=[0, 1]).set_index(('state', 'timestep'))
# df_state
multiindex = df_state.columns
multiindex[-1]
df_state.set_index(multiindex[-1], inplace=True)
# multiindex[idx[:,:,:,:,:,'timestep']]
# df_state.set_index(multiindex[idx[:,:,:,:,:,'timestep']], inplace=True)
df_state
# df_state.values


In [ ]:
idx = pd.IndexSlice
ser_decoded = pd.Series(dict_observations_list[0])
ser_decoded.index.names =[ 'episodestart', 'vehicle', 'driver', 'timestamp', 'qtuple', 'rows', 'idx']
ser_action = ser_decoded.loc[idx[:, :, :, :, 'action', ['r0', 'r1', 'r2', 'throttle']]]
df_action = ser_action.unstack([0,1,2,3,4,5])
multiindex = df_action.columns
df_action.set_index(multiindex[-1], inplace=True)

action_timestep = ser_decoded.loc[idx[:,:,:,:,'action', 'timestep']]
action_speed = ser_decoded.loc[idx[:,:,:,:,'action', 'speed']]
action_multicol = [
    (*column, speed, timestep)
    for column, timestep, speed in zip(df_action.columns, action_timestep, action_speed)
]
df_action.columns = pd.MultiIndex.from_tuples(
    action_multicol, names=['episodestart','vehicle','driver','timestamp','qtuple', 'rows', 'speed', 'timestep']
)
df_action


ser_state = ser_decoded.loc[idx[:,:,:,:,'state', ['brake', 'thrust', 'velocity', 'timestep']]]
df_state = ser_state.unstack([0,1,2,3,4,5])
multiindex = df_state.columns
df_state.set_index(multiindex[-1], inplace=True)
df_state


ser_nstate = ser_decoded.loc[idx[:,:,:,:,'nstate', ['brake', 'thrust', 'velocity', 'timestep']]]
df_nstate = ser_nstate.unstack([0,1,2,3,4,5])
multiindex = df_nstate.columns
df_nstate.set_index(multiindex[-1], inplace=True)
df_nstate



In [ ]:
ser_reward = ser_decoded.loc[idx[:,:,:,:,'reward', ['work', 'timestep']]]
# ser_reward = pd.Series(
#     data=[ser_reward[('reward', 'work', 0)]],
#     index=[ser_reward[('reward', 'timestep', 0)]],
#     name='work',
# )
ser_reward = ser_reward.unstack([0,1,2,3,4,5])
multiindex = ser_reward.columns
ser_reward.set_index(multiindex[-1], inplace=True)
ser_reward

In [ ]:
# ser_reward = ser_decoded.loc[idx[:,:,:,:,'reward', ['work', 'timestep']]]
# ser_reward = pd.Series(
#     data=[ser_reward[multiindex[0]]],
#     index=[ser_reward[multiindex[1]]],
#     name='work',
# )
# ser_reward

In [ ]:
df_actions = []
df_states = []
df_nstates = []
ser_rewards = []

for dict_observations in dict_observations_list:
    idx = pd.IndexSlice
    ser_decoded = pd.Series(dict_observations)
    ser_decoded.index.names =[ 'episodestart', 'vehicle', 'driver', 'timestamp', 'qtuple', 'rows', 'idx']

    ser_action = ser_decoded.loc[idx[:, :, :, :, 'action', ['r0', 'r1', 'r2', 'throttle']]]
    df_action = ser_action.unstack([0,1,2,3,4,5])
    multiindex = df_action.columns
    df_action.set_index(multiindex[-1], inplace=True)

    action_timestep = ser_decoded.loc[idx[:,:,:,:,'action', 'timestep']]
    action_speed = ser_decoded.loc[idx[:,:,:,:,'action', 'speed']]
    action_multicol = [
        (*column, speed, timestep)
        for column, timestep, speed in zip(df_action.columns, action_timestep, action_speed)
    ]
    df_action.columns = pd.MultiIndex.from_tuples(
        action_multicol, names=['episodestart','vehicle','driver','timestamp','qtuple', 'rows', 'speed', 'timestep']
    )
    # df_action
    df_actions.append(df_action)


    ser_state = ser_decoded.loc[idx[:,:,:,:,'state', ['brake', 'thrust', 'velocity', 'timestep']]]
    df_state = ser_state.unstack([0,1,2,3,4,5])
    multiindex = df_state.columns
    df_state.set_index(multiindex[-1], inplace=True)
    # df_state
    df_states.append(df_state)


    ser_nstate = ser_decoded.loc[idx[:,:,:,:,'nstate', ['brake', 'thrust', 'velocity', 'timestep']]]
    df_nstate = ser_nstate.unstack([0,1,2,3,4,5])
    multiindex = df_nstate.columns
    df_nstate.set_index(multiindex[-1], inplace=True)
    # df_nstate
    df_nstates.append(df_nstate)

    ser_reward = ser_decoded.loc[idx[:,:,:,:,'reward', ['work', 'timestep']]]
    ser_reward = ser_reward.unstack([0,1,2,3,4,5])
    multiindex = ser_reward.columns
    ser_reward.set_index(multiindex[-1], inplace=True)
    # ser_reward
    ser_rewards.append(ser_reward)


### simply concatenate the pandas dataframes leads to confusion
please see the following.


In [ ]:
df_actions_all = pd.concat(df_actions)
df_actions_all

### the following is the correct way to extract columns, index and values from the pandas dataframes

and stack them into numpy arrays for further analysis

In [ ]:
npa_action_columns_list = [df_action.columns for df_action in df_actions]
# npa_action_columns_list
npa_action_indices_list = [df_action.index for df_action in df_actions]
# npa_action_indices_list
npa_state_columns_list = [df_state.columns for df_state in df_states]
npa_state_indices_list = [df_state.index for df_state in df_states]
npa_nstate_columns_list = [df_nstate.columns for df_nstate in df_nstates]
npa_nstate_indices_list = [df_nstate.index for df_nstate in df_nstates]
npa_reward_columns_list = [ser_reward.columns for ser_reward in ser_rewards]
npa_reward_indices_list = [ser_reward.index for ser_reward in ser_rewards]

In [ ]:
npa_action_columns_list[0]
npa_action_indices_list[0]
ts_array = []
for columns in npa_action_columns_list:
    timestep = columns.get_level_values('timestep')
    ts_array.append(timestep)
    # print(timestep)
    # print(npa_action_columns_list[0].loc[idx[:,:,:,timestep,:,:], :])
    # print(npa_action_indices_list[0].loc[idx[:,:,:,timestep,:,:], :])

ts_array = pd.DataFrame(np.stack(ts_array).T)
ts_array
ts_array.describe()
# ts_array.average()

In [ ]:
npa_reward_columns_list[0]
npa_reward_indices_list[0]

In [ ]:
df_states[0]
df_states[0].values.flatten()
df_states[0].loc[:, idx[:,:,:,:,'state',['velocity','thrust','brake']]] ## keep the order of input
df_states[0].loc[:, idx[:,:,:,:,'state',['velocity','thrust','brake']]].values.flatten()
# df_actions[0]
# df_actions[0].values.flatten()

In [ ]:
npa_states_list = [df_state.loc[:,idx[:,:,:,:,'state',['velocity', 'thrust', 'brake']]].values.T.flatten() for df_state in df_states]  # transpose T is necessary for column-wise stacking and flatten
npa_states = np.stack(npa_states_list).astype('float')
npa_states


npa_actions_list = [df_action.loc[:, idx[:,:,:,:,'action',['r0', 'r1', 'r2']]].values.T.flatten() for df_action in df_actions]
npa_actions = np.stack(npa_actions_list).astype('float')
npa_actions

npa_rewards_list = [ser_reward.values.T.flatten() for ser_reward in ser_rewards]
npa_rewards = np.stack(npa_rewards_list).astype('float')
npa_rewards

npa_nstates_list = [df_nstate.loc[:,idx[:,:,:,:,'nstate', ['velocity', 'thrust', 'brake']]].values.T.flatten() for df_nstate in df_nstates]
npa_nstates = np.stack(npa_nstates_list).astype('float')
npa_nstates

# np.concatenate(df_actions.values)

In [ ]:
type(npa_states)
npa_states


In [ ]:
npa_actions

In [ ]:
npa_nstates

In [ ]:
npa_rewards

In [ ]:
# df_action = ser_action.unstack(level=[0, 1]).set_index(('action', 'throttle'))
# action_timestep = ser_decoded.loc[('action', 'timestep')]
# action_speed = ser_decoded.loc[('action', 'speed')]
#
# action_multicol = [
#     (*column, speed, timestep)
#     for column, timestep, speed in zip(df_action.columns, action_timestep, action_speed)
# ]
# df_action.columns = pd.MultiIndex.from_tuples(
#     action_multicol, names=['qtuple', 'rows', 'speed', 'timestep']
# )
# df_action
# df_action.values.flatten()
#
# ser_state = ser_decoded.loc[:, idx['state', ['brake', 'thrust', 'velocity', 'timestep']]]
# # ser_state
# df_state = ser_state.unstack(level=[0, 1]).set_index(('state', 'timestep'))
# df_state
#
# df_state.values
#
# ser_nstate = ser_decoded.loc[:, idx['nstate', ['brake', 'thrust', 'velocity', 'timestep']]]
# # ser_state
# df_nstate = ser_nstate.unstack(level=[0, 1]).set_index(('nstate', 'timestep'))
# df_nstate
#
# ser_reward = ser_decoded.loc[:, idx['reward', ['work', 'timestep']]]
# ser_reward = pd.Series(
#     data=[ser_reward[('reward', 'work', 0)]],
#     index=[ser_reward[('reward', 'timestep', 0)]],
#     name='work',
# )
# ser_reward

In [ ]:


# ser_decoded = pd.Series(dict_observations)
# ser_action = ser_decoded.loc[('action', ['r0', 'r1', 'r2', 'throttle'])]
# df_action = ser_action.unstack(level=[0, 1]).set_index(('action', 'throttle'))
# action_timestep = ser_decoded.loc[('action', 'timestep')]
# action_speed = ser_decoded.loc[('action', 'speed')]
#
# action_multicol = [
#     (*column, speed, timestep)
#     for column, timestep, speed in zip(df_action.columns, action_timestep, action_speed)
# ]
# df_action.columns = pd.MultiIndex.from_tuples(
#     action_multicol, names=['qtuple', 'rows', 'speed', 'timestep']
# )
# df_action
# df_action.values.flatten()
#
# ser_state = ser_decoded.loc[('state', ['brake', 'thrust', 'velocity', 'timestep'])]
# # ser_state
# df_state = ser_state.unstack(level=[0, 1]).set_index(('state', 'timestep'))
# df_state
#
# df_state.values
#
# ser_nstate = ser_decoded.loc[('nstate', ['brake', 'thrust', 'velocity', 'timestep'])]
# # ser_state
# df_nstate = ser_nstate.unstack(level=[0, 1]).set_index(('nstate', 'timestep'))
# df_nstate
#
# ser_reward = ser_decoded.loc[('reward', ['work', 'timestep'])]
# ser_reward = pd.Series(
#     data=[ser_reward[('reward', 'work', 0)]],
#     index=[ser_reward[('reward', 'timestep', 0)]],
#     name='work',
# )
# ser_reward


## Encoding sampled multiple episodes from Mongo episode documents to multiindexed DataFrame

### generate mutliple episodes of mongo episode docs

In [ ]:
dfs_episode

## create epsiode with different lengths

In [ ]:

dfs_episodex = dfs_episode.copy()
dfs_episodex.index = dfs_episodex.index.set_levels([episodestart], level='episodestart')
dfs_episodex.index = dfs_episodex.index.set_levels(
    [[trucks_by_id['VB4'].vid], [drivers_by_id['li-changlong'].pid]],
    level=['vehicle', 'driver'],
    verify_integrity=False,
)
dfs_episodex
ts_index = dfs_episodex.index.unique(level='timestamp')

idx_num = len(ts_index)
drop_num = np.random.randint(low=1, high=idx_num-1)
ts_index_to_drop = np.random.choice(ts_index, drop_num,replace=False)
ts_index_to_drop
dfs_zigzag =dfs_episodex.drop(index=ts_index_to_drop, level='timestamp')
dfs_zigzag

In [ ]:
ts_new = pd.to_datetime((datetime.now()))
ts_new
episodestart = ts_new - pd.Timedelta(2, 'd')
episodestart

dfs_episode0 = dfs_episode.copy()
dfs_episode0.index = dfs_episode0.index.set_levels([episodestart], level='episodestart')
dfs_episode0.index = dfs_episode0.index.set_levels(
    [[trucks_by_id['VB7'].vid], [drivers_by_id['zheng-longfei'].pid]],
    level=['vehicle', 'driver'],
    verify_integrity=False,
)
ts_index = dfs_episode0.index.unique(level='timestamp')
idx_num = len(ts_index)
drop_num = np.random.randint(low=1, high=idx_num-1)
ts_index_to_drop = np.random.choice(ts_index, drop_num,replace=False)
dfs_episode0 =dfs_episode0.drop(index=ts_index_to_drop, level='timestamp')

dfs_episode1 = dfs_episode.copy()
dfs_episode1.index = dfs_episode1.index.set_levels(
    [episodestart - pd.Timedelta(3, 'd')], level='episodestart'
)
dfs_episode1.index = dfs_episode1.index.set_levels(
    [[trucks_by_id['MP73'].vid], [drivers_by_id['wang-cheng'].pid]],
    level=['vehicle', 'driver'],
    verify_integrity=False,
)
ts_index = dfs_episode1.index.unique(level='timestamp')
idx_num = len(ts_index)
drop_num = np.random.randint(low=1, high=idx_num-1)
ts_index_to_drop = np.random.choice(ts_index, drop_num,replace=False)
dfs_episode1 =dfs_episode1.drop(index=ts_index_to_drop, level='timestamp')

dfs_episode2 = dfs_episode.copy()
dfs_episode2.index = dfs_episode2.index.set_levels(
    [episodestart - pd.Timedelta(4, 'd')], level='episodestart'
)
dfs_episode2.index = dfs_episode2.index.set_levels(
    [[trucks_by_id['VB7'].vid], [drivers_by_id['wang-cheng'].pid]],
    level=['vehicle', 'driver'],
    verify_integrity=False,
)
ts_index = dfs_episode2.index.unique(level='timestamp')
idx_num = len(ts_index)
drop_num = np.random.randint(low=1, high=idx_num-1)
ts_index_to_drop = np.random.choice(ts_index, drop_num,replace=False)
dfs_episode2 =dfs_episode2.drop(index=ts_index_to_drop, level='timestamp')

dfs_episode3 = dfs_episode.copy()
dfs_episode3.index = dfs_episode3.index.set_levels(
    [episodestart - pd.Timedelta(5, 'd')], level='episodestart'
)
dfs_episode3.index = dfs_episode3.index.set_levels(
    [[trucks_by_id['MP73'].vid], [drivers_by_id['zheng-longfei'].pid]],
    level=['vehicle', 'driver'],
    verify_integrity=False,
)

ts_index = dfs_episode3.index.unique(level='timestamp')
idx_num = len(ts_index)
drop_num = np.random.randint(low=1, high=idx_num-1)
ts_index_to_drop = np.random.choice(ts_index, drop_num,replace=False)
dfs_episode3 =dfs_episode3.drop(index=ts_index_to_drop, level='timestamp')
dfs_episode3

In [ ]:
from functools import reduce

episodes = [dfs_episode, dfs_episode0, dfs_episode1, dfs_episode2, dfs_episode3]
try:
    dfs_episode_all = reduce(
        lambda left, right,: pd.concat([left, right], axis=0), episodes
    )
except Exception as e:
    print(e)
# dfs_episode_all.sort_index(inplace=True)
# dfs_episode_all = dfs_episode_all.swaplevel(1, 0, axis=0)
# dfs_episode_all = dfs_episode_all.swaplevel(1, 2, axis=0)
dfs_episode_all.sort_index(inplace=True)
dfs_episode_all = dfs_episode_all[['state', 'action', 'reward', 'nstate']]
display('dfs_episode_all')
dfs_episode_all.index
dfs_episode_all.columns

In [ ]:
docs = []
for episode in episodes:
    dict_nested = eos_df_to_nested_dict(episode)
    indices_dict = [
        {indices.names[i]: level for i, level in enumerate(levels)} for levels in episode.index
    ]
    single_key_dict = {idx['timestamp']: dict_nested[key] for idx, key in zip(indices_dict, dict_nested)}

    episode_meta = indices_dict[0].copy()
    try:
        episode_meta.pop('timestamp')
    except KeyError:
        print(f"Key 'timestamp' not found")

    episode_meta['seq_len'] = len(single_key_dict)

    meta = {**(observation_meta.model_dump()), **episode_meta}

    doc = DataFrameDoc(timestamp=meta['episodestart'], meta=meta, observation=single_key_dict,)
    docs.append(doc)

docs

### encode multiple episodes of mongo documents to DataFrames

In [ ]:
df_docs = pd.DataFrame(docs)
df_docs

In [ ]:
dict_observations = [
    {key: value for key, value in row.items()} for row in df_docs['observation']
]
dict_observations

### decoding observations (episodes)

In [ ]:
dict_observations = {(meta['vehicle'], meta['driver'], meta['episodestart'], key1, key2, key3, key4): value
                        for meta, obs in zip(df_docs['meta'],df_docs['observation'])
                        for key1, obs1 in obs.items()
                        for key2, obs2 in obs1.items()
                        for key3, obs3 in obs2.items()
                        for key4, value in obs3.items()}

dict_observations
len(dict_observations)

In [ ]:
ser_decoded = pd.Series(dict_observations)
ser_decoded.index.names = ['vehicle', 'driver','episodestart', 'timestamp', 'qtuple', 'rows', 'idx']
ser_decoded
df_decoded = ser_decoded.unstack(level=['qtuple', 'rows', 'idx'])
df_decoded

In [ ]:
episodestart_index = df_decoded.index.unique(level='episodestart')
# rewards.values
episodestart_index

df_rewards = df_decoded['reward','work']
# rewards.index.get_level_values('episodestart')
idx = pd.IndexSlice
np_r_n_t = [ df_rewards.loc[idx[:,:,ep_start, :]].values.tolist()   for ep_start in episodestart_index]
# np_r_n_t = [ rewards.loc[:,:,ep_start].values.tolist()   for ep_start in episodestart_index]
np_r_n_t
np_r_n_t[0]

In [ ]:
df_rewards.loc[:,:,episodestart_index[0]]

In [ ]:
from keras.utils import pad_sequences

r_n_t = pad_sequences(np_r_n_t, padding='post', dtype='float32', value=-10000.0)
r_n_t
r_n_t.shape

In [ ]:

idx = pd.IndexSlice
states = df_decoded.loc[:, idx['state',['velocity', 'thrust', 'brake']]]
states

In [ ]:
np_s_n_t = [states.loc[idx[:,:,ep_start, :]].values.tolist() 
            for ep_start in episodestart_index]
s_n_t = pad_sequences(np_s_n_t, padding='post', dtype='float32', value=-10000.0)
print(s_n_t)
s_n_t.shape


In [ ]:
torque_table_row_names = ['r0', 'r1', 'r2']
actions = df_decoded.loc[:, idx['action', torque_table_row_names]]
np_a_n_t = [actions.loc[idx[:,:,ep_start, :]].values.tolist() for ep_start in episodestart_index]
a_n_t = pad_sequences(np_a_n_t, padding='post', dtype='float32', value=-10000.0)
print(a_n_t)
a_n_t.shape


In [ ]:
s_n_t.shape
a_n_t.shape
s_n_t
a_n_t

In [ ]:
idx = pd.IndexSlice
nstates = df_decoded.loc[:, idx['nstate',['velocity', 'thrust', 'brake']]]
print(nstates)
np_ns_n_t = [nstates.loc[idx[:,:,ep_start, :]].values.tolist() 
            for ep_start in episodestart_index]
ns_n_t = pad_sequences(np_ns_n_t, padding='post', dtype='float32', value=-10000.0)
print(ns_n_t)
ns_n_t.shape


In [ ]:
s_n_t_ = s_n_t[:,1:, :]
s_n_t_.shape
s_n_t_
a_n_t_ = a_n_t[:,:-1, :]
a_n_t_.shape
a_n_t_

h_n_t = np.concatenate((s_n_t_, a_n_t_), axis=2)
h_n_t.shape
h_n_t

# split batches into trucated sequences for TBPTT

In [ ]:
obs_n_t = zip(s_n_t, a_n_t, r_n_t, ns_n_t)
type(obs_n_t)

In [ ]:
s_n_t
s_n_t.shape

In [ ]:
split_num = s_n_t.shape[1]//2+1
print(f'split_num: {split_num}')
s_n_t_splits = np.array_split(s_n_t,split_num, axis=1)
len(s_n_t_splits)
s_n_t_splits[0]
s_n_t_splits[1]
s_n_t_splits[2]

In [ ]:
split_num = s_n_t.shape[1]//2+1
print(f'split_num: {split_num}')

for i, batch_t in enumerate(zip(np.array_split(s_n_t,split_num, axis=1),
                   np.array_split(a_n_t,split_num, axis=1),
                   np.array_split(r_n_t,split_num, axis=1),
                   np.array_split(ns_n_t,split_num, axis=1))):
    s_n_t_b, a_n_t_b, r_n_t_b, ns_n_t_b = batch_t
    print(f'batch number: {i}')
    print(f's_n_t_b: {s_n_t_b}')
    print(f'a_n_t_b: {a_n_t_b}')
    print(f'r_n_t_b: {r_n_t_b}')
    print(f'ns_n_t_b: {ns_n_t_b}')